pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                dir('project5-builddockerimage') {
                    sh 'docker build -t jenkins-project5-demo .'
                }
            }
        }

        stage('Verify Docker Image') {
            steps {
                sh 'docker images | grep jenkins-project5-demo'
            }
        }
    }

    post {
        success {
            echo 'Docker image built successfully using Jenkins.'
        }

        failure {
            echo 'Docker image build failed.'
        }
    }
}
